# Dinámica de sistemas cuánticos

Consideremos un sistema compuesto de $N$ espines 1/2, descrito por el `Hamiltonian` ($\hbar = 1$):

\begin{equation}
\hat{H} = \sum_{i=1}^{N-1} J\hat{\sigma}^z_i \hat{\sigma}^z_{i+1} + \sum_{i=1}^N g\hat{\sigma}^x_i,
\end{equation}

donde el primer término corresponde a una interacción de vecinos cercanos en la dirección $z$, mientras que el segundo término genera dinámica coherente entre los espines que componen el sistema. El `Hamiltonian` anterior es el Hamiltoniano del modelo de Ising cuántico de ferromagnetismo en una dimensión.

El estado de un objeto cuántico, usualmente se denota por el símbolo $| \psi \rangle$ en el marco de la segunda cuantización y esto es conocido como un `estado puro`. Sin embargo, los sistemas cuánticos no necesarimente se encuentran en estados puros, si no que puede estar en un `estado mixto`. Un `estado mixto` es una colección clásica de estados cuánticos y se representan por medio del `operador de la matrix de densidad`:
\begin{equation}
\hat{\rho} = \sum_i p_i |\psi_i \rangle \langle \psi_i |,
\end{equation}
donde $p_i$ son valores de una distribución de probabilidad clásica, de manera tal que $\sum_i p_i = 1$ para asegurar normalización. Al contrario de un `estado puro`, un `estado mixto` es un operador que se representa mediante una matriz en el espacio de Hilbert.

Lo más importante, es que la dinámica de un `estado mixto` se describe mediante la `ecuación de von Neumann`, al contrario de la dinámica de un `estado puro` que se describe mediante la `ecuación de Schrödinger`. La `ecuación de von Neumann` está dada por
\begin{equation}
\frac{d\hat{\rho}(t)}{dt} = -{\rm{i}} [\hat{H}, \hat{\rho}(t)],
\end{equation}
para el caso especial de un Hamiltoniano que no depende del tiempo. [A, B] = AB - BA es el conmutador cuántico.

Vamos a resolver la `ecuación de Von Neumann` para el sistema de espines que describen el modelo de Ising cuántico.

Es mecánica cuántica, usualmente nos interesan los `valores de expectación`, que corresponden a los valores que podemos medir experimentalmente. Utilizando `estados mixtos`, los valores de expectación se calculan con la traza:
\begin{equation}
\langle \hat{O} \rangle (t) = {\rm{Tr}}[\hat{O}\hat{\rho}(t)].
\end{equation}

### Caso para N espines

ESTO HAY QUE CAMBIARLO PARA EL CASO DE N ESPINES

Para $N=2$, podemos construir el `Hamiltonian` denotado al inicio utilizando productos tensoriales de cada uno de los espacios de Hilbert que componen el sistema. Por ejemplo:
\begin{equation}
\hat{\sigma}^z_1 = \hat{\sigma}^z \otimes \mathbb{1}, \\
\hat{\sigma}^z_2 = \mathbb{1} \otimes \hat{\sigma}^z, \\
\hat{\sigma}^x_1 = \hat{\sigma}^x \otimes \mathbb{1}, \\
\hat{\sigma}^x_2 = \mathbb{1} \otimes \hat{\sigma}^x, \\
\end{equation}
donde $\otimes$ corresponde al producto tensorial y $\mathbb{1}$ a la matrix identidad $2x2$.

`NumPy` nos permite representar dichos operadores como una matrices en el espacio de Hilbert.

Primero definimos las matrices de Pauli para un espín 1/2:

In [209]:
import qutip as qt # Librería QuTip
import numpy as np # Librería Numpy

In [210]:
sx = qt.sigmax() # Pauli X
sz = qt.sigmaz() # Pauli Z

iden = qt.qeye(2) # Identidad de tamaño N

Y con éstas podemos representar el `Hamiltonian` utilizando el producto tensorial (`np.kron`):

In [215]:
# Calcule el Hamiltoniano del model de Ising usando productos tensoriales de las matrices de Pauli

# Esta rutina debe devolver una matrix 2^Nx2^N que corresponde al modelo de Ising para N espines

def hamiltonian(J, g, N):
    
    sigma_z = []
    sigma_x = []
    
    for i in range(N):
        
        sigma_zi = []
        sigma_xi = []
        
        for j in range(i):
            
            sigma_zi.append(iden)  
            sigma_xi.append(iden)
        
        sigma_zi.append(sz)   
        sigma_xi.append(sx)
        
        for k in range(i+1,N):
                
            sigma_zi.append(iden)
            sigma_xi.append(iden)
        
        #print(sigma_zi[0])
        sigma_z.append(qt.tensor(sigma_zi)) # Producto tensorial de los elementos de sigma_zi
        sigma_x.append(qt.tensor(sigma_xi))
        

    
    h_first = 0.0
    h_second = 0.0
    
    for i in range(N-1):

        h_first += J*np.dot(sigma_z[i], sigma_z[i+1])
        #print(np.dot(sigma_z[i], sigma_z[i+1]))

    for i in range(N):

        h_second += g*np.array(sigma_x[i])
    
    #print(h_first)
    #print(h_second)
    return np.real(h_first + h_second)


La matriz es una $2^Nx 2^N$ que describe la dinámica interna del sistema:

In [217]:
N = 2
print(hamiltonian(2.0, 1.0, N))

[[ 2.  1.  1.  0.]
 [ 1. -2.  0.  1.]
 [ 1.  0. -2.  1.]
 [ 0.  1.  1.  2.]]
